import Head from "next/head";
import { CreateGameForm } from "../components/CreateGame";
import { ActiveGames } from "../components/ActiveGames";
import styled from "styled-components";
import { useState } from "react";
import { nanoid } from "nanoid";

export default function Home() {
  const [myGames, setMyGames] = useState([]);

  function newGame({ gameName, gamePlayers }) {
    const newGame = {
      game: gameName,
      players: gamePlayers.map((name) => ({
        name: name,
        score: 0,
        id: nanoid,
      })),
      isActive: true,
      gameId: nanoid,
    };

    setMyGames([...myGames, newGame]);
  }

  function increase(playerid, gameid) {
    console.log("click");
    const anyGameIndex = myGames.findIndex(
      (element) => element.gameId === gameid
    );
    const anyPlayerIndex = myGames[anyGameIndex].players.findIndex(
      (element) => element.id === playerid
    );

    setMyGames(
      myGames.map((element) =>
        element.index === anyGameIndex
          ? {
              ...element,
              players: element.players.map((element) =>
                element.index === anyPlayerIndex ? element.score++ : element
              ),
            }
          : element
      )
    );
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <FlexFrame>
          <CreateGameFrame>
            <CreateGameForm newGame={newGame} />
          </CreateGameFrame>
          <ActiveGamesFrame>
            <ActiveGames myGames={myGames} increase={increase} />
          </ActiveGamesFrame>
        </FlexFrame>
      </main>
    </div>
  );
}

const FlexFrame = styled.div`
  display: flex;
  padding: 3rem;
  gap: 3rem;
`;

const CreateGameFrame = styled.div`
  width: 500px;
  display: flex;
  padding-top: 2rem;
  border: 2px dotted gray;
  padding: 1rem;
`;

const ActiveGamesFrame = styled.div`
  width: 500px;
  display: flex;
  padding-top: 2rem;
  border: 2px dotted gray;
  padding: 1rem;
`;
